name: Build ScamsungKernel Selinux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      kernel_repo:
        description: 'Kernel Repository URL'
        required: true
      kernel_branch:
        description: 'Git branch'
        required: false
      clang_version:
        description: 'Pilih Versi Clang Compiler'
        required: true
        default: 'clang-10'
        type: choice
        options: ['clang-10', 'clang-11', 'clang-12', 'proton-clang', 'azure-clang']
      defconfig_name:
        description: 'Nama Defconfig'
        required: true
        default: 'vendor/a23_eur_open_defconfig'
      selinux_mode:
        description: 'Pilih Mode SELinux'
        required: true
        default: 'permissive'
        type: choice
        options: ['enforcing', 'permissive']

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout WorkSpace
      uses: actions/checkout@v4

    - name: Environment Setup
      run: |
        sudo apt update && sudo apt install -y zip ccache bc cpio flex bison git python-is-python3 libc6 libc6-dev tar perl curl lz4
        
        REPO="${{ github.event.inputs.kernel_repo || 'ISI_URL_REPO_DEFAULT_DISINI' }}"
        BRANCH="${{ github.event.inputs.kernel_branch }}"
        
        if [ -z "$BRANCH" ]; then
          git clone --depth=1 --recursive "$REPO" $GITHUB_WORKSPACE/kernel_src
        else
          git clone --depth=1 -b "$BRANCH" --recursive "$REPO" $GITHUB_WORKSPACE/kernel_src
        fi

        mkdir -p $GITHUB_WORKSPACE/toolchains && cd $GITHUB_WORKSPACE/toolchains
        CHOSEN_CLANG="${{ github.event.inputs.clang_version || 'clang-10' }}"
        
        if [ "$CHOSEN_CLANG" = "proton-clang" ]; then
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git clang
        elif [ "$CHOSEN_CLANG" = "azure-clang" ]; then
          git clone --depth=1 https://github.com/Padd3X/Azure-Clang.git clang
        else
          git clone --depth=1 -b "$CHOSEN_CLANG" https://github.com/rsuplaygrnd/toolchains.git clang
        fi
        git clone --depth=1 -b gcc https://github.com/blxyzY/toolchain.git gcc

    - name: Compile Kernel
      run: |
        export PATH="$GITHUB_WORKSPACE/toolchains/clang/bin:$GITHUB_WORKSPACE/toolchains/gcc/bin:$PATH"
        export ARCH=arm64 SUBARCH=arm64 OUT_DIR=$GITHUB_WORKSPACE/out USE_CCACHE=1 CCACHE_DIR=~/.cache/ccache
        export GCC_64=aarch64-linux-android- GCC_32=arm-linux-androideabi-
        
        ccache -M 5G && mkdir -p $OUT_DIR && cd $GITHUB_WORKSPACE/kernel_src
        
        # --- FIX KERNELSU INTEGRATION & COMPATIBILITY ---
        echo "Menyelaraskan struktur KernelSU..."
        rm -rf drivers/kernelsu
        git clone https://github.com/tiann/KernelSU.git drivers/kernelsu
        
        echo "Menambal file_wrapper.c untuk kompatibilitas kernel lama..."
        mkdir -p drivers/kernelsu/infra/
        cat << 'EOF' > drivers/kernelsu/
